name: CF Pages Deploy

on:
    push:
      branches:
        - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5c5866bc9a741374b75a7accbb71ab2e
          projectName: arknights-toolbox
          directory: dist/
        #   gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
        #   workingDirectory: my-site
        #   wranglerVersion: '3'