name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
          
      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Set Config
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.OSS_KEY }}
          access-key-secret: ${{ secrets.OSS_SECRET }}

      - name: Delete Files
        run: |
          ossutil rm -rf oss://arknights-toolbox/
      
      - name: Upload Files
        run: |
          ossutil cp -j 200 -rf dist/ oss://arknights-toolbox/

      - name: Get API Access Token
        run: |
          ACCESS_TOKEN=$(curl -s -X POST http://${{ secrets.CDN_API }}/APIAccessTokenService/getAPIAccessToken -d '{"type": "admin", "accessKeyId": "${{ secrets.CDN_ACCESSKEYID }}", "accessKey": "${{ secrets.CDN_ACCESSKEY }}"}' | jq -r '.data.token')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Cache purge Task
        run: |
          ACCESS_TOKEN=$ACCESS_TOKEN
          curl -X POST http://${{ secrets.CDN_API }}/HTTPCacheTaskService/createHTTPCacheTask -H "X-Edge-Access-Token: $ACCESS_TOKEN" -d '{"type": "purge", "keyType": "prefix", "keys": ["https://moeyy.cn/arknights"]}'
